version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-browsers
        environment:
          MAVEN_OPTS: -Xmx1024m
    working_directory: ~/project/testng
    steps:
    - checkout:
        path: ~/project
    - run:
        name: Browsers versions
        command: |
          chromedriver --version
          google-chrome --version
          geckodriver --version
          firefox --version
    - run:
        name: Download CM Selenoid
        command: curl -s https://aerokube.com/cm/bash | bash
    - run:
        name: Run CM Selenoid
        command: ./cm selenoid start --browsers chrome --use-drivers & curl http://127.0.0.1:4444/status
        background: true
    - restore_cache:
        keys:
          - $CIRCLE_PROJECT_REPONAME-{{ checksum "pom.xml" }}
          - $CIRCLE_PROJECT_REPONAME-

    - run:
        name: Resolve Maven dependencies
        command: mvn dependency:go-offline compile compiler:testCompile
    - run:
        name: Curl
        command: sleep 30 & curl http://127.0.0.1:4444/status
    - run: curl -XPOST http://127.0.0.1:4444/session -d '{"desiredCapabilities":{"browserName":"chrome"}}'
    - run:
        name: Autotests
        command: mvn test -Dstaging=${STAGING:-alpha} -Dsurefire.suiteXmlFiles=${SUITE:-all}.xml
    - run:
        name: Generate environment properties
        command: echo -e "BUILD_NUM=$CIRCLE_BUILD_NUM \nstaging=${STAGING:-alpha}" >> target/allure-results/environment.properties
        when: always

    - run:
        name: Make history dir for allure
        command: mkdir target/allure-results/history
        when: always
    - run:
        name: Get previous artifact links
        command: curl https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts?circle-token=$artifacts | grep -o 'https:\/\/[^"]*Allure\/history\/.*\.json' > artifacts.txt || true
        when: always
    - run: cat artifacts.txt
    - run:
        name: Download history artfacts
        command: <artifacts.txt xargs -P4 -I % wget %?circle-token=$artifacts
        when: always
    - run:
        name: Rename and copy history artifacts to allure-result
        command: |
          mv history.json?circle-token=$artifacts history.json && mv history-trend.json?circle-token=$artifacts history-trend.json || true
          cp history.json target/allure-results/history/ && cp history-trend.json target/allure-results/history/ || true
          mv categories-trend.json?circle-token=$artifacts categories-trend.json && mv duration-trend.json?circle-token=$artifacts duration-trend.json || true
          cp categories-trend.json target/allure-results/history/ && cp duration-trend.json target/allure-results/history/ || true
          mv retry-trend.json?circle-token=$artifacts retry-trend.json || true
          cp retry-trend.json target/allure-results/history/ || true
        when: always

    - run:
        name: Allure Report
        command: mvn allure:report
        when: always

    - save_cache:
        paths:
          - ~/.m2
          - .allure
        key: $CIRCLE_PROJECT_REPONAME-{{ checksum "pom.xml" }}
        when: always
    - store_test_results:
        path: target/surefire-reports/junitreports
    - store_artifacts:
        path: target/surefire-reports
        #destination: report/testng-results
    - store_artifacts:
        path: target/allure-results
        #destination: report/allure-results
    - store_artifacts:
        path: target/site/allure-maven-plugin
        destination: Allure

workflows:
  version: 2
  autotests_and_report:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build